-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 09:30:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Onela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Onela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Onela` DEFAULT CHARACTER SET utf8 ;
USE `Onela` ;

-- -----------------------------------------------------
-- Table `Onela`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onela`.`Contact` (
  `idContact` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(60) NOT NULL,
  `lastname` VARCHAR(60) NOT NULL,
  `phone_number` VARCHAR(30) NOT NULL,
  `active` INT NOT NULL,
  PRIMARY KEY (`idContact`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onela`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onela`.`Group` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onela`.`Contact_has_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onela`.`Contact_has_Group` (
  `Contact_idContact` INT NOT NULL,
  `Group_idGroup` INT NOT NULL,
  PRIMARY KEY (`Contact_idContact`, `Group_idGroup`),
  INDEX `fk_Contact_has_Group_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  INDEX `fk_Contact_has_Group_Contact_idx` (`Contact_idContact` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_has_Group_Contact`
    FOREIGN KEY (`Contact_idContact`)
    REFERENCES `Onela`.`Contact` (`idContact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_has_Group_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Onela`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
