CREATE USER 'User'@'localhost' IDENTIFIED BY 'Pa$$w0rd';
GRANT USAGE ON *.* TO 'User'@'localhost';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `onela`.* TO 'User'@'localhost';
FLUSH PRIVILEGES;